### PR TITLE
allow array for audience and scope claims

### PR DESCRIPTION
**Pull request by dkendall**
I hereby consent to the Individual CLA provided in assets/cla/individual_cla.md

### CODE REVIEW

**Comment by greenpau** [comment]
@dkendall , thank you for the PR! 👍  Could you please add a unit test for this use case?, i.e. multiple aud entries vs single one?

**Comment by dkendall** [comment]
> Could you please add a unit test for this use case?, i.e. multiple aud entries vs single one?

@greenpau Please take a look at the latest commit and let me know if that's what you had in mind.

**Comment by dkendall** [comment]
@greenpau I should have put different features on separate branches, but now all the work for the issues I opened is in this PR, along with several unit tests.

**Comment by greenpau** [comment]
@dkendall , i apologize but this review will take some time. I just started a new job. Weekends is the only time when I can review this.

**Comment by greenpau** [comment]
@dkendall , the one think I would like to ask you is figuring out a way to output the aud as string when audience has only 1 item. Currently, you will always output a list.

**Comment by dkendall** [comment]
> @dkendall , the one think I would like to ask you is figuring out a way to output the aud as string when audience has only 1 item. Currently, you will always output a list.

@greenpau Are you referring to AsMap in user.go?

**Comment by greenpau** [comment]
@dkendall , i don’t remember. What I care about is that things work well here: https://github.com/greenpau/caddy-auth-portal/blob/a56fc4f223b28e543d7a4c99c7edf7cc423dce3b/pkg/handlers/login.go#L110

**Comment by greenpau** [comment]
@dkendall , more specifically GetToken or GetSignedToken here https://github.com/greenpau/caddy-auth-portal/blob/a56fc4f223b28e543d7a4c99c7edf7cc423dce3b/pkg/handlers/login.go#L75

**Comment by dkendall** [comment]
> @dkendall , more specifically GetToken or GetSignedToken here https://github.com/greenpau/caddy-auth-portal/blob/a56fc4f223b28e543d7a4c99c7edf7cc423dce3b/pkg/handlers/login.go#L75

@greenpau Ah, okay... I'll convert the "aud" and "scope" claims to a space-separated list in a single string, copy user.go over to the jet pkg in the portal, and run the portal unit tests.

**Comment by dkendall** [comment]
> @dkendall , more specifically GetToken or GetSignedToken here https://github.com/greenpau/caddy-auth-portal/blob/a56fc4f223b28e543d7a4c99c7edf7cc423dce3b/pkg/handlers/login.go#L75

@greenpau I changed the code so a single "aud" claim is stored as a string, and multiples are stored as an array, per the standard.

https://tools.ietf.org/html/rfc7519#section-4.1.3

I also made a change so the scope claim is a space-separated list.

I've confirmed that neither UserClaims.Audience nor UserClaims.Scope are used in the portal, which builds and passes its tests with the updated user.go. The "aud" claim also isn't used, and "scope" is used only in oauth2 backend.go where it's stored in an array named Scopes.

**Comment by greenpau** [comment]
@dkendall , LGTM! Really great job on the amendments and testing! 👍 
Next time, please try splitting into separate PRs 😉 
Great contribution! 👏

**Pull request merged**
